[book]
authors = ["wangchao"]
language = "en"
multilingual = false
src = "src"
title = "前端文档笔记"

[build]
build-dir = "docs"

[output.html]
no-section-label = true

[output.html.fold]
enable=true
level=1
